from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import pandas as pd
import tabula
import pdfplumber
import io
import os
import json
import traceback

app = Flask(__name__)
CORS(app)

@app.route('/health', methods=['GET'])
def health_check():
    """Check if API is running"""
    return jsonify({'status': 'online', 'message': 'Python backend with tabula-py ready'})

@app.route('/convert', methods=['POST'])
def convert_file():
    """Convert uploaded file (PDF/CSV/Excel) to structured data"""
    try:
        if 'file' not in request.files:
            return jsonify({'error': 'No file provided'}), 400
        
        file = request.files['file']
        filename = file.filename.lower()
        
        if filename.endswith('.pdf'):
            # Use tabula-py for PDF extraction
            try:
                # Save temporarily
                temp_path = '/tmp/temp_pdf.pdf'
                file.save(temp_path)
                
                # Extract tables
                tables = tabula.read_pdf(temp_path, pages='all', multiple_tables=True)
                
                # Clean up
                os.remove(temp_path)
                
                if not tables or all(t.empty for t in tables):
                    return jsonify({'error': 'No tables found in PDF'}), 400
                
                # Combine all non-empty tables
                valid_tables = [t for t in tables if not t.empty]
                df = pd.concat(valid_tables, ignore_index=True)
                
            except Exception as e:
                # Fallback to pdfplumber
                file.seek(0)
                with pdfplumber.open(file) as pdf:
                    all_data = []
                    for page in pdf.pages:
                        tables = page.extract_tables()
                        for table in tables:
                            if table and len(table) > 1:
                                headers = table[0]
                                rows = table[1:]
                                for row in rows:
                                    if any(row):
                                        row_dict = {}
                                        for i, header in enumerate(headers):
                                            if i < len(row):
                                                row_dict[header] = row[i] if row[i] else ''
                                        all_data.append(row_dict)
                    df = pd.DataFrame(all_data)
        
        elif filename.endswith('.csv'):
            df = pd.read_csv(file)
            
        elif filename.endswith(('.xlsx', '.xls')):
            df = pd.read_excel(file)
            
        else:
            return jsonify({'error': 'Unsupported file type'}), 400
        
        # Data cleaning
        if not df.empty:
            # Remove empty rows
            df = df.dropna(how='all')
            
            # Clean column names
            df.columns = [str(col).strip().replace(' ', '_') for col in df.columns]
            
            # Try to detect and convert date columns
            for col in df.columns:
                if 'date' in col.lower():
                    try:
                        df[col] = pd.to_datetime(df[col], errors='coerce')
                    except:
                        pass
            
            # Try to detect and clean currency columns
            for col in df.select_dtypes(include=['object']).columns:
                if df[col].astype(str).str.contains(r'\$|€|£', regex=True).any():
                    df[col] = df[col].astype(str).str.replace(r'[$€£,]', '', regex=True)
                    df[col] = pd.to_numeric(df[col], errors='coerce')
        
        # Convert to JSON for frontend preview
        preview_data = df.head(100).fillna('').to_dict(orient='records')
        
        return jsonify({
            'success': True,
            'data': preview_data,
            'total_rows': len(df),
            'columns': list(df.columns),
            'source': 'python-tabula' if filename.endswith('.pdf') else 'python-pandas'
        })
        
    except Exception as e:
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500

@app.route('/generate-excel', methods=['POST'])
def generate_excel():
    """Generate Excel file from processed data"""
    try:
        data = request.json.get('data', [])
        original_filename = request.json.get('filename', 'export')
        
        if not data:
            return jsonify({'error': 'No data provided'}), 400
        
        df = pd.DataFrame(data)
        
        # Add metadata
        metadata = pd.DataFrame({
            'Info': ['Generated by Python backend', 'Date', 'Source File'],
            'Value': [pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S'), original_filename]
        })
        
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            df.to_excel(writer, index=False, sheet_name='Extracted_Data')
            metadata.to_excel(writer, index=False, sheet_name='Metadata')
            
            # Add summary statistics if numeric columns exist
            numeric_cols = df.select_dtypes(include=['number']).columns
            if len(numeric_cols) > 0:
                summary = df[numeric_cols].describe()
                summary.to_excel(writer, sheet_name='Summary_Stats')
        
        output.seek(0)
        
        return send_file(
            output,
            mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            as_attachment=True,
            download_name=f'python_converted_{pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")}.xlsx'
        )
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/batch-process', methods=['POST'])
def batch_process():
    """Process multiple files at once"""
    try:
        files = request.files.getlist('files')
        all_data = []
        
        for file in files:
            filename = file.filename.lower()
            
            if filename.endswith('.pdf'):
                tables = tabula.read_pdf(file, pages='all')
                if tables:
                    df = pd.concat(tables, ignore_index=True)
                    df['source_file'] = filename
                    all_data.append(df)
                    
            elif filename.endswith('.csv'):
                df = pd.read_csv(file)
                df['source_file'] = filename
                all_data.append(df)
                
            elif filename.endswith(('.xlsx', '.xls')):
                df = pd.read_excel(file)
                df['source_file'] = filename
                all_data.append(df)
        
        if not all_data:
            return jsonify({'error': 'No valid files processed'}), 400
        
        combined_df = pd.concat(all_data, ignore_index=True)
        
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            combined_df.to_excel(writer, index=False, sheet_name='Combined_Data')
        
        output.seek(0)
        
        return send_file(
            output,
            mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            as_attachment=True,
            download_name=f'batch_export_{pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")}.xlsx'
        )
        
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True)
